### ISSUE TITLE
Clean up application code

### ISSUE THREAD

**Issue by scottbishopdev** [sbishop411/RoverInterviewProject#2]
Most of the code in this repo is pretty darn messy. We should go through and clean it up to my current standards. This issue will be used to track the cleanup of the actual application code.

**Comment by sbishop411** [comment]
As part of this issue, I'd like to update most of the file and directory names in the project to use proper camelCase (AKA dromedaryCase, as opposed to PascalCase).

**Comment by scottbishopdev** [comment]
The [Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html#source-file-structure) suggests using filenames that are all lowercase, and can include underscores and hyphens. As a result, I think we should use [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Special_case_styles) for file and directory naming conventions. We should include these updates as part of this issue.

**Comment by scottbishopdev** [comment]
Since [Owner.js](https://github.com/sbishop411/RoverInterviewProject/blob/master/Src/server/models/Owner.js), Since [Sitter.js](https://github.com/sbishop411/RoverInterviewProject/blob/master/Src/server/models/Sitter.js), and [Stay.js](https://github.com/sbishop411/RoverInterviewProject/blob/master/Src/server/models/Stay.js) are all defining mongoose schemas, I'd like to rename the classes accordingly, and also place them in a "schemas" directory rather than a "models" directory. Once we [implement TypeScript](https://github.com/sbishop411/RoverInterviewProject/projects/6), this will give us a great place to store ES6 classes that define our models (and perhaps eventually our Schema as well, via [typegoose](https://typegoose.github.io/typegoose/)).

**Comment by scottbishopdev** [comment]
I've made the decision that cleanup of the front-end code contained in [public](https://github.com/sbishop411/RoverInterviewProject/tree/master/Src/public) is out of scope for this issue. Since we're going to be [replacing the current UI with a new one](https://github.com/sbishop411/RoverInterviewProject/projects/5), any refactoring that we do there will probably be wiped out soon anyway.
